// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN0PGSJtYzREsTrQPow5jBMttG1-GFpxE',
    appId: '1:43389722959:web:dfec178901f99e9b70e53a',
    messagingSenderId: '43389722959',
    projectId: 'daily-update-6e8e1',
    authDomain: 'daily-update-6e8e1.firebaseapp.com',
    storageBucket: 'daily-update-6e8e1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmPf9SNq3Od16wF6aDWBZL9qYmXxQBAeo',
    appId: '1:43389722959:android:635b239f5dd0302770e53a',
    messagingSenderId: '43389722959',
    projectId: 'daily-update-6e8e1',
    storageBucket: 'daily-update-6e8e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKF11wmDx6vXPHXzGKTL2Sh7ppMr8KAh0',
    appId: '1:43389722959:ios:e50c0686a3f6a2c070e53a',
    messagingSenderId: '43389722959',
    projectId: 'daily-update-6e8e1',
    storageBucket: 'daily-update-6e8e1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKF11wmDx6vXPHXzGKTL2Sh7ppMr8KAh0',
    appId: '1:43389722959:ios:e50c0686a3f6a2c070e53a',
    messagingSenderId: '43389722959',
    projectId: 'daily-update-6e8e1',
    storageBucket: 'daily-update-6e8e1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN0PGSJtYzREsTrQPow5jBMttG1-GFpxE',
    appId: '1:43389722959:web:b2d5421fa7d84cc670e53a',
    messagingSenderId: '43389722959',
    projectId: 'daily-update-6e8e1',
    authDomain: 'daily-update-6e8e1.firebaseapp.com',
    storageBucket: 'daily-update-6e8e1.firebasestorage.app',
  );
}
